Region.destroy_all

Region.create!([
  {name: "Coal River Valley", location: "27 Bridge Street, Richmond TAS 7025 Australia", region_lat: -42.73, region_long: 147.43, vintages: "Out of 10 =>  2009: 8\t2010: 9\t2011: 8\t2012: 9\t2013: 8\t2014: 9\t2015: 9      ", region_description: "The Coal River region surrounding Richmond is an award winning wine producing area with a similar latitude to the famous wine regions of France and Germany. Only a 20 minute scenic drive from the city and you are amongst the largest concentration of privately owned vineyards in Tasmania.", region_varieties: "Pinot Noir, Carbernet Sauvignon, Merlot, Chardonnay and Sauvignon Blanc ", region_img: "ylhramwpm8ii4fwvlgbn", region_event: nil, region_event_date: nil},
  {name: "Derwent Valley", location: "Granton TAS 7030 Australia", region_lat: -42.75, region_long: 147.23, vintages: "Out of 10 =>  2009: 8\t2010: 9\t2011: 8\t2012: 9\t2013: 8\t2014: 9\t2015: 9      ", region_description: "West of Hobart, where the road follows the beautiful Derwent River through rows of poplars and on to Tasmania’s central highlands and the grandeur of Lake St Clair and the Tasmanian Wilderness World Heritage Area.", region_varieties: "Pinot Noir,,  Chardonnay and Sauvignon Blanc ", region_img: "kmnx07h8wvece1u1y2gr", region_event: nil, region_event_date: nil},
  {name: "East Coast Tasmania", location: "Swansea TAS 7190 Australia", region_lat: -42.13, region_long: 148.06, vintages: "Out of 10 =>  2009: 8\t2010: 8\t2011: 7\t2012: 8\t2013: 7\t2014: 8\t2015: 8", region_description: "Yes, it’s picture-perfect, white sand beaches and open, endless blue horizons. It’s places that make you feel like you’re the first person to leave a footprint. It’s national parks filled with wonders, and seaside towns filled with welcome. It’s a gourmet food bowl bursting with the best local fare matched to full-flavoured wines, harvested from the east coast wine route’s boutique vineyards.", region_varieties: "Pinot Noir,  Chardonnay and Riesling ", region_img: "ose9isrbf1fibhdwkcsb", region_event: nil, region_event_date: nil},
  {name: "Huon Valley", location: "Ranelagh TAS 7109 Australia", region_lat: -43.02, region_long: 147.03, vintages: "Out of 10 =>  2009: 8\t2010: 9\t2011: 8\t2012: 9\t2013: 8\t2014: 9\t2015: 9      ", region_description: "Australia's southernmost wines are produced in Southern Tasmania's Huon Valley. There are five boutique wineries to select, all within 25 minutes drive of Walton House in Huonville. Award winning Pinot Noirs are elegant, the Chardonnays sharp and light, but aromatic Rieslings are the pick of the whites.", region_varieties: "Pinot Noir,  Chardonnay and Riesling ", region_img: "yzpnbmc73wnvnftoawfm", region_event: nil, region_event_date: nil},
  {name: "North West Tasmania", location: "Spreyton TAS 7310 Australia", region_lat: -41.22, region_long: 146.35, vintages: "Out of 10 =>  2009: 8\t2010: 8\t2011: 7\t2012: 8\t2013: 7\t2014: 8\t2015: 8", region_description: "The North West Tasmania Wine Region inlcudes the area near Burnie and Devonport on the northern coastline, and extends inland to Sheffield and Barrington. The area includes two districts - Coastal and Inland, because of the major climatic differences.", region_varieties: "Sav Blanc, Chardonnay and Pinot Noir", region_img: "rdxelx4kfkgc7ijymwpd", region_event: nil, region_event_date: nil},
  {name: "Tamar Valley", location: "Beaconsfield TAS Australia", region_lat: -41.2, region_long: 146.82, vintages: "Out of 10 =>  2009: 8\t2010: 8\t2011: 7\t2012: 8\t2013: 7\t2014: 8\t2015: 8", region_description: "Over 30 cellar doors across 170kms. Our unique cool climate location produces elegant wines of exceptional quality. From the Valley, to Pipers River in the north and Relbia in the south, there’s over 32 wineries within driving distance of each other.  Tamar Valley varieties of note are Chardonnay, Riesling, Sauvignon Blanc, Pinot Noir, Cabernet Sauvignon and Merlot. .", region_varieties: "Pinot Noir, Carbernet Sauvignon, Merlot, Chardonnay and Sauvignon Blanc ", region_img: "mzuw3cmc6lnkjyhshk2b", region_event: nil, region_event_date: nil}
])

Traveller.destroy_all

Traveller.create!([
  {first_name: "Bill", last_name: "Murray", email: "bill@gmail.com", image: "pqkhkyaywo8ivklt7slq", dob: nil, password: "chicken", password_confirmation: "chicken", admin: false, phone: "", city: "New York", country: "US", lat: nil, long: nil, fav_winery: "Silver Oak", fav_region: "Bolgheri", fav_variety: nil, location: nil},
  {first_name: "Bruce", last_name: "Jenner", email: "bruce@gmail.com", image: "lopu0vdt7z5kh22nirmp", dob: "1956-03-04", password: "chicken", password_confirmation: "chicken", admin: false, phone: "", city: "", country: "", lat: nil, long: nil, fav_winery: "Pink winery", fav_region: "Any region making rose", fav_variety: nil, location: nil},
  {first_name: "Lucy", last_name: "Liu", email: "lucy@gmail.com", image: "rtc8xsvsdmaa2agdyyzu", dob: nil, password: "chicken", password_confirmation: "chicken", admin: false, phone: "", city: "", country: "", lat: nil, long: nil, fav_winery: "Woodlands Wines", fav_region: "Oregon", fav_variety: nil, location: nil},
  {first_name: "Donald", last_name: "Trump", email: "donald@gmail.com", image: "uywv5qodeqe9wod1d6az", dob: nil, password: "chicken", password_confirmation: "chicken", admin: false, phone: "", city: "", country: "", lat: nil, long: nil, fav_winery: "Who cares, lets make America great again!", fav_region: "", fav_variety: nil, location: nil},
  {first_name: "Cher", last_name: "Are you kidding me, I have no last name, I'm Cher", email: "cher@gmail.com", image: "x4lfohhyrrndpkjsawue", dob: nil, password: "chicken", password_confirmation: "chicken", admin: false, phone: "", city: "", country: "", lat: nil, long: nil, fav_winery: "Opus One", fav_region: "Chianti Region", fav_variety: nil, location: nil},
  {first_name: "Barrack", last_name: "Obama", email: "barrack@gmail.com", image: "ommseouarlidxnurszst", dob: nil, password: "chicken", password_confirmation: "chicken", admin: false, phone: "", city: "", country: "", lat: nil, long: nil, fav_winery: "Any where I can get drunk,  America is going down!", fav_region: "Who cares, America is going down!", fav_variety: nil, location: nil},
  {first_name: "Luis", last_name: "Guzman", email: "luis@gmail.com", image: "een81glampb8nmwtoqaj", dob: nil, password: "chicken", password_confirmation: "chicken", admin: false, phone: "", city: "", country: "Mexico", lat: nil, long: nil, fav_winery: "Any winery with free tasting", fav_region: "Los Carneros", fav_variety: nil, location: nil}
])

Winery.destroy_all

Winery.create!([
  {name: "Bay of Fires Winery", winery_image: "wtwjzrexui3wwhnwvmdb", winery_admin: false, is_winery: nil, is_certified: nil, rating: "5 stars", email: "cellardoor@bayoffireswines.com.au", website: "http://www.bayoffireswines.com.au/", winery_lat: -41.1139465, winery_long: 147.0922141, feature_wine: nil, winery_description: nil, winery_pitch: "The winery was founded upon the vision and spirit of our dedicated winemaking and viticultural team, who believed Tasmania would one day be the pre-eminent region in Australia to produce cool climate wines. To this end, we search for the individual 'personalities' in every variety and vineyard, to craft wines which are unique, alluring and distinctively Tasmanian but never compromise on consistency or quality.", must_try_wines: "Bays of Fire Pinot Noir and Bays of Fire Pinot Gris", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: 7, winery_location: "40 Baxters Rd, Pipers River TAS 7252"},
  {name: "Delamere Vineyard", winery_image: "q0euiqpiocccskmmsgyu", winery_admin: false, is_winery: nil, is_certified: nil, rating: "4 stars", email: "shane@delamerevineyards.com.au", website: "http://www.delamerevineyards.com.au", winery_lat: -41.0710157, winery_long: 147.1627535, feature_wine: nil, winery_description: nil, winery_pitch: "Our passion for the region of Tasmania, at similar latitude to the Champagne and Burgundy regions in France, arises from a desire to seek out a genuine cold climate that can produce wines of classic structure, combining fruit intensity with refinement, complexity with persistence of flavour, and the ultimate expression and grape and region.", must_try_wines: "Vintage Blanc de Blanc and Delamere Pinot Noir", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: 7, winery_location: "4238 Bridport Rd, Pipers Brook TAS 7254"},
  {name: "Devils Corner", winery_image: "auwqosjlaqxmx8pmvzac", winery_admin: false, is_winery: nil, is_certified: nil, rating: "4 stars", email: "info@devilscorner.com.au", website: "https://www.brownbrothers.com.au/about-us/our-brands/devils-corner/", winery_lat: -41.9792215, winery_long: 148.1583481, feature_wine: nil, winery_description: nil, winery_pitch: "On Tasmania’s beautiful East Coast you’ll find Devil’s Corner Cellar Door, home to Australia’s most popular Pinot Noir. Enjoy a tasting of the Devil’s Corner range of wines while looking over ‘The Hazards’ on the Freycinet Peninsular and Moulting Lagoon, a wetland of international environmental significance.", must_try_wines: "Mt Amos Pinot Noir and Resolution Pinot Noi", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: nil, winery_location: " Sherbourne Rd, Apslawn TAS 7190"},
  {name: "Domaine A", winery_image: "u38txcmflnxuabcjuvmn", winery_admin: false, is_winery: nil, is_certified: nil, rating: "5 stars", email: "althaus@domaine-a.com.au", website: "http://www.domaine-a.com.au/", winery_lat: -42.678171, winery_long: 147.4191145, feature_wine: nil, winery_description: nil, winery_pitch: "Our passion for the region of Tasmania, at similar latitude to the Champagne and Burgundy regions in France, arises from a desire to seek out a genuine cold climate that can produce wines of classic structure, combining fruit intensity with refinement, complexity with persistence of flavour, and the ultimate expression and grape and region.", must_try_wines: "Domaine A Cabernet Sauvignon and Domaine A Petit a Cabernets", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: 9, winery_location: "105 Tea Tree Road Campania, Tasmania AUSTRALIA 7026"},
  {name: "Freycinet Vineyards", winery_image: "yagvf1ytztzkqb04acoy", winery_admin: false, is_winery: nil, is_certified: nil, rating: "3 stars", email: "info@freycinetvineyard.com.au", website: "http://www.freycinetvineyard.com.au/", winery_lat: -41.8956978, winery_long: 148.2569074, feature_wine: nil, winery_description: nil, winery_pitch: "Absolute dedication, no compromise  Inspired by the tremendous opportunities of the East Coast of Tasmania, Geoff and Susan Bull cleared the site in 1978, planted the first vines in 1979 and established the first commerical winery on the East Coast.  They were early pioneers in a new region which years later revealed exciting quality potential in wines.  The Freycinet Vineyard and Winery is family owned with daughter Lindy Bull and her partner Claudio Radenti taking over the family tradition of gently handcrafting the wines.", must_try_wines: "Wineglass Bay Sauvignon Blanc and Freycinet Pinot Noir  ", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: nil, winery_location: "15919 Tasman Hwy, Bicheno TAS 7215"},
  {name: "Holm Oak Vineyards", winery_image: "nc3wuue1kxoemyqgbcdc", winery_admin: false, is_winery: nil, is_certified: nil, rating: "5 stars", email: "admin@holmoakvineyards.com.au", website: "http://www.holmoakvineyards.com.au", winery_lat: -41.1789976, winery_long: 146.9180046, feature_wine: nil, winery_description: nil, winery_pitch: "ituated somewhat off the beaten track our cellar door exudes an irresistible rustic charm. Our property is adorned with fabulous old English trees and our cellar door is situated in the original vertical board winery.", must_try_wines: "Wizard Pinot Noir and  Wizard Chardonnay", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: 7, winery_location: "11 W Bay Rd, Rowella TAS 7270"},
  {name: "Home Hill Winery", winery_image: nil, winery_admin: false, is_winery: nil, is_certified: nil, rating: "5 stars", email: "info@homehillwines.com.au", website: "http://www.homehillwines.com.au", winery_lat: -43.0024, winery_long: 147.0428, feature_wine: nil, winery_description: nil, winery_pitch: "A small family affair covering 6ha of 25 years old vines – mostly Pinot Noir, Chardonnay and Sylvaner, Home Hill has quickly emerged as one of Tasmania’s most awarded pinot producers. Sharing the same latitude of Bordeaux and featuring a fantastic restaurant and a friendly atmosphere, this cool climate winery is a must when visiting the Huon Valley.", must_try_wines: "Kellys Reserve Chardonnay and Kellys Reserve Pinot Noir", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: 9, winery_location: "38 Nairn Rd, Ranelagh TAS 7109 Australia"},
  {name: "Milton Vineyard", winery_image: nil, winery_admin: false, is_winery: nil, is_certified: nil, rating: "3 stars", email: "wine@miltonvineyard.com.au", website: "https://miltonvineyard.com.au", winery_lat: -42.0250, winery_long: 148.0529, feature_wine: nil, winery_description: nil, winery_pitch: " First farmed in 1826 for fine Tasmanian wool, Milton is now producing fine cool climate wines. Located on the dry sunny Freycinet Coast of Tasmania, its 13 ha produce cool climate Pinot Noir and aromatic whites.", must_try_wines: "Sparkling Laura and Pinot Noir", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: 9, winery_location: " 14635 Tasman Hwy, Swansea TAS 7190 Australia"},
  {name: "Moores Hill", winery_image: "vzrcsbipwgovwhubyea0", winery_admin: false, is_winery: nil, is_certified: nil, rating: "5 stars", email: "info@mooreshill.com.au", website: "http://www.mooreshill.com.au", winery_lat: -41.239802, winery_long: 146.878311, feature_wine: nil, winery_description: nil, winery_pitch: "Moore's Hill Estate is a boutique, family-operated wine producer located in the beautiful Tamar Valley in Tasmania, Australia. We take great pride in our specialty — estate grown, single vineyard wines of outstanding depth, quality and personality.", must_try_wines: "Pinot Noir and Riesling", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: 7, winery_location: "3343 W Tamar Hwy, Sidmouth TAS 7270"},
  {name: "Pooley Wines", winery_image: "zfee35np8vvgfwckd9gu", winery_admin: false, is_winery: nil, is_certified: nil, rating: "5 stars", email: "enquiries@pooleywines.com.au", website: "http://pooleywines.com.au", winery_lat: -42.7388225, winery_long: 147.4283022, feature_wine: nil, winery_description: nil, winery_pitch: "Pooley Wines has an historical property and two separate vineyards in the Coal River Valley in southern Tasmania. The Coal River Valley has developed a worldwide reputation, and is ideally suited, for the production of cool-climate wines such as Pinot Noir, Riesling and Chardonnay. ", must_try_wines: "Cooinda Vale Pinot Noir and Butchers Hill Pinot Noir", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: 9, winery_location: "1431 Richmond Rd, Richmond TAS 7025"},
  {name: "Stefano Lubiana", winery_image: nil, winery_admin: false, is_winery: nil, is_certified: nil, rating: "5 stars", email: "bookings@slw.com.au", website: "https://slw.com.au", winery_lat: -42.7498, winery_long: 147.2034, feature_wine: nil, winery_description: nil, winery_pitch: " Steve and Monique Lubiana brought their experience to Tasmania 30 years ago, producing some of the finest Sparklings in the country. Biodinamically cultivated, the 25ha also produce some smart whites and a solid Pinot Noir. A great option for lunch as the restaurant is top-notch.", must_try_wines: "Brut Rose and Estate Pinot Noir", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: true, restaurant: true, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: 9, winery_location: "60 Rowbottoms Rd, Granton TAS 7030 Australia"},
  {name: "Tolpuddle Vineyard", winery_image: nil, winery_admin: false, is_winery: nil, is_certified: nil, rating: "5 stars", email: "info@tolpuddlevineyard.com", website: "http://www.tolpuddlevineyard.com", winery_lat: -42.7379, winery_long: 147.4299, feature_wine: nil, winery_description: nil, winery_pitch: " Established in 1988, Tolpuddle crafts superb cool climate wines with great flavour, intensity and precision from its mature Chardonnay and Pinot Noir vines. Unfortunately no tasting is available but feel free to email them and ask for a private tour.", must_try_wines: "Tolpuddle Vineyard Pinot Noir", winery_event: nil, winery_event_date: nil, visit_app_only: nil, cellar_door: false, restaurant: false, rest_name: nil, open_time_cd: nil, close_time_cd: nil, open_days_cd: nil, open_time_rest: nil, close_time_rest: nil, open_days_rest: nil, region_id: 9, winery_location: "37 Back Tea Tree Road, Richmond, TAS 7025 Australia"}
])
Traveller.first.wineries << Winery.first << Winery.second
Winery.first.travellers << Traveller.first << Traveller.second
Region.first.wineries << Winery.fourth << Winery.tenth << Winery.twelfth
Region.second.wineries << Winery.eleventh
Region.third.wineries << Winery.third << Winery.fifth << Winery.eighth
Region.fourth.wineries << Winery.seventh
Region.sixth.wineries << Winery.first << Winery.second << Winery.sixth << Winery.ninth
